# Generated by Django 3.2.7 on 2021-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
